# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: auth_postgres
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: secret123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - auth-network

volumes:
  postgres_data:

networks:
  auth-network:
